development:
  #detalhes boleto simples integration
  api_token:        -J04vfs8S0jIItnM-RIVJzo1xuhd6guxwOs3FuQZWUM
  IP_PORT_SERV:     192.168.0.250  

  #detalhes sendgrid integration
  SMTP_USER_NAME:   apikey
  API_KEY_SENDGRID: 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   
  DOMAIN_NAME:      intra.anoregce.org.br
  boleto_simples_enviroment: sandbox
  boleto_simples_user_agent: gust904@gmail.com
  boleto_simples_api_token:  -J04vfs8S0jIItnM-RIVJzo1xuhd6guxwOs3FuQZWUM
production:   
  boleto_simples_enviroment: production
  boleto_simples_user_agent: intranet@anoregce.org.br
  boleto_simples_api_token:  mYbEbQK3XEAwa0QbdVWMu8XcS8FMdEteTdNcLT6R4ww
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  #detalhes boleto simples integration
  api_token:        -J04vfs8S0jIItnM-RIVJzo1xuhd6guxwOs3FuQZWUM
  IP_PORT_SERV:     192.168.0.250  
  environment: production
  #detalhes sendgrid integration
  SMTP_USER_NAME:   apikey
  API_KEY_SENDGRID: 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   
  DOMAIN_NAME:      intra.anoregce.org.br