default: &default
  adapter: postgresql
  encoding: unicode 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: anoreg_intranet_dev
  username: postgres
  password: 123456
  host: localhost

test:
  <<: *default
  database: anoreg_intranet_test
  username: postgres
  password: 123456
  host: localhost

production:
  <<: *default
  database: database_anoreg_intranet_production
  username: postgres
  password: 123456 