class PopularContrib < ActiveRecord::Migration[6.1] 
  Intranet::Contribuicao.create(descricao: "GRUPO 01", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 02", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 03", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 04", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 05", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 06", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 07", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 08", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 09", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 10", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 11", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 12", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 13", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 14", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 15", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 16", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 17", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 18", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 19", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 20", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 21", ativo: true)
  Intranet::Contribuicao.create(descricao: "GRUPO 22", ativo: true)
end
