class PopulateIntranetCidade < ActiveRecord::Migration[6.1] 
	Intranet::Cidade.create(municipio:"Abaiara",estado:"CE",cod_ibge:2300101)
	Intranet::Cidade.create(municipio:"Acarape",estado:"CE",cod_ibge:2300150)
	Intranet::Cidade.create(municipio:"Acaraú",estado:"CE",cod_ibge:2300200)
	Intranet::Cidade.create(municipio:"Acopiara",estado:"CE",cod_ibge:2300309)
	Intranet::Cidade.create(municipio:"Aiuaba",estado:"CE",cod_ibge:2300408)
	Intranet::Cidade.create(municipio:"Alcântaras",estado:"CE",cod_ibge:2300507)
	Intranet::Cidade.create(municipio:"Altaneira",estado:"CE",cod_ibge:2300606)
	Intranet::Cidade.create(municipio:"Alto Santo",estado:"CE",cod_ibge:2300705)
	Intranet::Cidade.create(municipio:"Amontada",estado:"CE",cod_ibge:2300754)
	Intranet::Cidade.create(municipio:"Antonina do Norte",estado:"CE",cod_ibge:2300804)
	Intranet::Cidade.create(municipio:"Apuiarés",estado:"CE",cod_ibge:2300903)
	Intranet::Cidade.create(municipio:"Aquiraz",estado:"CE",cod_ibge:2301000)
	Intranet::Cidade.create(municipio:"Aracati",estado:"CE",cod_ibge:2301109)
	Intranet::Cidade.create(municipio:"Aracoiaba",estado:"CE",cod_ibge:2301208)
	Intranet::Cidade.create(municipio:"Ararendá",estado:"CE",cod_ibge:2301257)
	Intranet::Cidade.create(municipio:"Araripe",estado:"CE",cod_ibge:2301307)
	Intranet::Cidade.create(municipio:"Aratuba",estado:"CE",cod_ibge:2301406)
	Intranet::Cidade.create(municipio:"Arneiroz",estado:"CE",cod_ibge:2301505)
	Intranet::Cidade.create(municipio:"Assaré",estado:"CE",cod_ibge:2301604)
	Intranet::Cidade.create(municipio:"Aurora",estado:"CE",cod_ibge:2301703)
	Intranet::Cidade.create(municipio:"Baixio",estado:"CE",cod_ibge:2301802)
	Intranet::Cidade.create(municipio:"Banabuiú",estado:"CE",cod_ibge:2301851)
	Intranet::Cidade.create(municipio:"Barbalha",estado:"CE",cod_ibge:2301901)
	Intranet::Cidade.create(municipio:"Barreira",estado:"CE",cod_ibge:2301950)
	Intranet::Cidade.create(municipio:"Barro",estado:"CE",cod_ibge:2302008)
	Intranet::Cidade.create(municipio:"Barroquinha",estado:"CE",cod_ibge:2302057)
	Intranet::Cidade.create(municipio:"Baturité",estado:"CE",cod_ibge:2302107)
	Intranet::Cidade.create(municipio:"Beberibe",estado:"CE",cod_ibge:2302206)
	Intranet::Cidade.create(municipio:"Bela Cruz",estado:"CE",cod_ibge:2302305)
	Intranet::Cidade.create(municipio:"Boa Viagem",estado:"CE",cod_ibge:2302404)
	Intranet::Cidade.create(municipio:"Brejo Santo",estado:"CE",cod_ibge:2302503)
	Intranet::Cidade.create(municipio:"Camocim",estado:"CE",cod_ibge:2302602)
	Intranet::Cidade.create(municipio:"Campos Sales",estado:"CE",cod_ibge:2302701)
	Intranet::Cidade.create(municipio:"Canindé",estado:"CE",cod_ibge:2302800)
	Intranet::Cidade.create(municipio:"Capistrano",estado:"CE",cod_ibge:2302909)
	Intranet::Cidade.create(municipio:"Caridade",estado:"CE",cod_ibge:2303006)
	Intranet::Cidade.create(municipio:"Cariré",estado:"CE",cod_ibge:2303105)
	Intranet::Cidade.create(municipio:"Caririaçu",estado:"CE",cod_ibge:2303204)
	Intranet::Cidade.create(municipio:"Cariús",estado:"CE",cod_ibge:2303303)
	Intranet::Cidade.create(municipio:"Carnaubal",estado:"CE",cod_ibge:2303402)
	Intranet::Cidade.create(municipio:"Cascavel",estado:"CE",cod_ibge:2303501)
	Intranet::Cidade.create(municipio:"Catarina",estado:"CE",cod_ibge:2303600)
	Intranet::Cidade.create(municipio:"Catunda",estado:"CE",cod_ibge:2303659)
	Intranet::Cidade.create(municipio:"Caucaia",estado:"CE",cod_ibge:2303709)
	Intranet::Cidade.create(municipio:"Cedro",estado:"CE",cod_ibge:2303808)
	Intranet::Cidade.create(municipio:"Chaval",estado:"CE",cod_ibge:2303907)
	Intranet::Cidade.create(municipio:"Choró",estado:"CE",cod_ibge:2303931)
	Intranet::Cidade.create(municipio:"Chorozinho",estado:"CE",cod_ibge:2303956)
	Intranet::Cidade.create(municipio:"Coreaú",estado:"CE",cod_ibge:2304004)
	Intranet::Cidade.create(municipio:"Crateús",estado:"CE",cod_ibge:2304103)
	Intranet::Cidade.create(municipio:"Crato",estado:"CE",cod_ibge:2304202)
	Intranet::Cidade.create(municipio:"Croatá",estado:"CE",cod_ibge:2304236)
	Intranet::Cidade.create(municipio:"Cruz",estado:"CE",cod_ibge:2304251)
	Intranet::Cidade.create(municipio:"Deputado Irapuan Pinheiro",estado:"CE",cod_ibge:2304269)
	Intranet::Cidade.create(municipio:"Ereré",estado:"CE",cod_ibge:2304277)
	Intranet::Cidade.create(municipio:"Eusébio",estado:"CE",cod_ibge:2304285)
	Intranet::Cidade.create(municipio:"Farias Brito",estado:"CE",cod_ibge:2304301)
	Intranet::Cidade.create(municipio:"Forquilha",estado:"CE",cod_ibge:2304350)
	Intranet::Cidade.create(municipio:"Fortaleza",estado:"CE",cod_ibge:2304400)
	Intranet::Cidade.create(municipio:"Fortim",estado:"CE",cod_ibge:2304459)
	Intranet::Cidade.create(municipio:"Frecheirinha",estado:"CE",cod_ibge:2304509)
	Intranet::Cidade.create(municipio:"General Sampaio",estado:"CE",cod_ibge:2304608)
	Intranet::Cidade.create(municipio:"Graça",estado:"CE",cod_ibge:2304657)
	Intranet::Cidade.create(municipio:"Granja",estado:"CE",cod_ibge:2304707)
	Intranet::Cidade.create(municipio:"Granjeiro",estado:"CE",cod_ibge:2304806)
	Intranet::Cidade.create(municipio:"Groaíras",estado:"CE",cod_ibge:2304905)
	Intranet::Cidade.create(municipio:"Guaiúba",estado:"CE",cod_ibge:2304954)
	Intranet::Cidade.create(municipio:"Guaraciaba do Norte",estado:"CE",cod_ibge:2305001)
	Intranet::Cidade.create(municipio:"Guaramiranga",estado:"CE",cod_ibge:2305100)
	Intranet::Cidade.create(municipio:"Hidrolândia",estado:"CE",cod_ibge:2305209)
	Intranet::Cidade.create(municipio:"Horizonte",estado:"CE",cod_ibge:2305233)
	Intranet::Cidade.create(municipio:"Ibaretama",estado:"CE",cod_ibge:2305266)
	Intranet::Cidade.create(municipio:"Ibiapina",estado:"CE",cod_ibge:2305308)
	Intranet::Cidade.create(municipio:"Ibicuitinga",estado:"CE",cod_ibge:2305332)
	Intranet::Cidade.create(municipio:"Icapuí",estado:"CE",cod_ibge:2305357)
	Intranet::Cidade.create(municipio:"Icó",estado:"CE",cod_ibge:2305407)
	Intranet::Cidade.create(municipio:"Iguatu",estado:"CE",cod_ibge:2305506)
	Intranet::Cidade.create(municipio:"Independência",estado:"CE",cod_ibge:2305605)
	Intranet::Cidade.create(municipio:"Ipaporanga",estado:"CE",cod_ibge:2305654)
	Intranet::Cidade.create(municipio:"Ipaumirim",estado:"CE",cod_ibge:2305704)
	Intranet::Cidade.create(municipio:"Ipu",estado:"CE",cod_ibge:2305803)
	Intranet::Cidade.create(municipio:"Ipueiras",estado:"CE",cod_ibge:2305902)
	Intranet::Cidade.create(municipio:"Iracema",estado:"CE",cod_ibge:2306009)
	Intranet::Cidade.create(municipio:"Irauçuba",estado:"CE",cod_ibge:2306108)
	Intranet::Cidade.create(municipio:"Itaiçaba",estado:"CE",cod_ibge:2306207)
	Intranet::Cidade.create(municipio:"Itaitinga",estado:"CE",cod_ibge:2306256)
	Intranet::Cidade.create(municipio:"Itapajé",estado:"CE",cod_ibge:2306306)
	Intranet::Cidade.create(municipio:"Itapipoca",estado:"CE",cod_ibge:2306405)
	Intranet::Cidade.create(municipio:"Itapiúna",estado:"CE",cod_ibge:2306504)
	Intranet::Cidade.create(municipio:"Itarema",estado:"CE",cod_ibge:2306553)
	Intranet::Cidade.create(municipio:"Itatira",estado:"CE",cod_ibge:2306603)
	Intranet::Cidade.create(municipio:"Jaguaretama",estado:"CE",cod_ibge:2306702)
	Intranet::Cidade.create(municipio:"Jaguaribara",estado:"CE",cod_ibge:2306801)
	Intranet::Cidade.create(municipio:"Jaguaribe",estado:"CE",cod_ibge:2306900)
	Intranet::Cidade.create(municipio:"Jaguaruana",estado:"CE",cod_ibge:2307007)
	Intranet::Cidade.create(municipio:"Jardim",estado:"CE",cod_ibge:2307106)
	Intranet::Cidade.create(municipio:"Jati",estado:"CE",cod_ibge:2307205)
	Intranet::Cidade.create(municipio:"Jijoca de Jericoacoara",estado:"CE",cod_ibge:2307254)
	Intranet::Cidade.create(municipio:"Juazeiro do Norte",estado:"CE",cod_ibge:2307304)
	Intranet::Cidade.create(municipio:"Jucás",estado:"CE",cod_ibge:2307403)
	Intranet::Cidade.create(municipio:"Lavras da Mangabeira",estado:"CE",cod_ibge:2307502)
	Intranet::Cidade.create(municipio:"Limoeiro do Norte",estado:"CE",cod_ibge:2307601)
	Intranet::Cidade.create(municipio:"Madalena",estado:"CE",cod_ibge:2307635)
	Intranet::Cidade.create(municipio:"Maracanaú",estado:"CE",cod_ibge:2307650)
	Intranet::Cidade.create(municipio:"Maranguape",estado:"CE",cod_ibge:2307700)
	Intranet::Cidade.create(municipio:"Marco",estado:"CE",cod_ibge:2307809)
	Intranet::Cidade.create(municipio:"Martinópole",estado:"CE",cod_ibge:2307908)
	Intranet::Cidade.create(municipio:"Massapê",estado:"CE",cod_ibge:2308005)
	Intranet::Cidade.create(municipio:"Mauriti",estado:"CE",cod_ibge:2308104)
	Intranet::Cidade.create(municipio:"Meruoca",estado:"CE",cod_ibge:2308203)
	Intranet::Cidade.create(municipio:"Milagres",estado:"CE",cod_ibge:2308302)
	Intranet::Cidade.create(municipio:"Milhã",estado:"CE",cod_ibge:2308351)
	Intranet::Cidade.create(municipio:"Miraíma",estado:"CE",cod_ibge:2308377)
	Intranet::Cidade.create(municipio:"Missão Velha",estado:"CE",cod_ibge:2308401)
	Intranet::Cidade.create(municipio:"Mombaça",estado:"CE",cod_ibge:2308500)
	Intranet::Cidade.create(municipio:"Monsenhor Tabosa",estado:"CE",cod_ibge:2308609)
	Intranet::Cidade.create(municipio:"Morada Nova",estado:"CE",cod_ibge:2308708)
	Intranet::Cidade.create(municipio:"Moraújo",estado:"CE",cod_ibge:2308807)
	Intranet::Cidade.create(municipio:"Morrinhos",estado:"CE",cod_ibge:2308906)
	Intranet::Cidade.create(municipio:"Mucambo",estado:"CE",cod_ibge:2309003)
	Intranet::Cidade.create(municipio:"Mulungu",estado:"CE",cod_ibge:2309102)
	Intranet::Cidade.create(municipio:"Nova Olinda",estado:"CE",cod_ibge:2309201)
	Intranet::Cidade.create(municipio:"Nova Russas",estado:"CE",cod_ibge:2309300)
	Intranet::Cidade.create(municipio:"Novo Oriente",estado:"CE",cod_ibge:2309409)
	Intranet::Cidade.create(municipio:"Ocara",estado:"CE",cod_ibge:2309458)
	Intranet::Cidade.create(municipio:"Orós",estado:"CE",cod_ibge:2309508)
	Intranet::Cidade.create(municipio:"Pacajus",estado:"CE",cod_ibge:2309607)
	Intranet::Cidade.create(municipio:"Pacatuba",estado:"CE",cod_ibge:2309706)
	Intranet::Cidade.create(municipio:"Pacoti",estado:"CE",cod_ibge:2309805)
	Intranet::Cidade.create(municipio:"Pacujá",estado:"CE",cod_ibge:2309904)
	Intranet::Cidade.create(municipio:"Palhano",estado:"CE",cod_ibge:2310001)
	Intranet::Cidade.create(municipio:"Palmácia",estado:"CE",cod_ibge:2310100)
	Intranet::Cidade.create(municipio:"Paracuru",estado:"CE",cod_ibge:2310209)
	Intranet::Cidade.create(municipio:"Paraipaba ",estado:"CE",cod_ibge:2310258)
	Intranet::Cidade.create(municipio:"Parambu",estado:"CE",cod_ibge:2310308)
	Intranet::Cidade.create(municipio:"Paramoti",estado:"CE",cod_ibge:2310407)
	Intranet::Cidade.create(municipio:"Pedra Branca",estado:"CE",cod_ibge:2310506)
	Intranet::Cidade.create(municipio:"Penaforte",estado:"CE",cod_ibge:2310605)
	Intranet::Cidade.create(municipio:"Pentecoste",estado:"CE",cod_ibge:2310704)
	Intranet::Cidade.create(municipio:"Pereiro",estado:"CE",cod_ibge:2310803)
	Intranet::Cidade.create(municipio:"Pindoretama",estado:"CE",cod_ibge:2310852)
	Intranet::Cidade.create(municipio:"Piquet Carneiro",estado:"CE",cod_ibge:2310902)
	Intranet::Cidade.create(municipio:"Pires Ferreira",estado:"CE",cod_ibge:2310951)
	Intranet::Cidade.create(municipio:"Poranga",estado:"CE",cod_ibge:2311009)
	Intranet::Cidade.create(municipio:"Porteiras",estado:"CE",cod_ibge:2311108)
	Intranet::Cidade.create(municipio:"Potengi",estado:"CE",cod_ibge:2311207)
	Intranet::Cidade.create(municipio:"Potiretama",estado:"CE",cod_ibge:2311231)
	Intranet::Cidade.create(municipio:"Quiterianópolis",estado:"CE",cod_ibge:2311264)
	Intranet::Cidade.create(municipio:"Quixadá",estado:"CE",cod_ibge:2311306)
	Intranet::Cidade.create(municipio:"Quixelô",estado:"CE",cod_ibge:2311355)
	Intranet::Cidade.create(municipio:"Quixeramobim",estado:"CE",cod_ibge:2311405)
	Intranet::Cidade.create(municipio:"Quixeré",estado:"CE",cod_ibge:2311504)
	Intranet::Cidade.create(municipio:"Redenção",estado:"CE",cod_ibge:2311603)
	Intranet::Cidade.create(municipio:"Reriutaba",estado:"CE",cod_ibge:2311702)
	Intranet::Cidade.create(municipio:"Russas",estado:"CE",cod_ibge:2311801)
	Intranet::Cidade.create(municipio:"Saboeiro",estado:"CE",cod_ibge:2311900)
	Intranet::Cidade.create(municipio:"Salitre",estado:"CE",cod_ibge:2311959)
	Intranet::Cidade.create(municipio:"Santa Quitéria",estado:"CE",cod_ibge:2312205)
	Intranet::Cidade.create(municipio:"Santana do Acaraú",estado:"CE",cod_ibge:2312007)
	Intranet::Cidade.create(municipio:"Santana do Cariri",estado:"CE",cod_ibge:2312106)
	Intranet::Cidade.create(municipio:"São Benedito",estado:"CE",cod_ibge:2312304)
	Intranet::Cidade.create(municipio:"São Gonçalo do Amarante",estado:"CE",cod_ibge:2312403)
	Intranet::Cidade.create(municipio:"São João do Jaguaribe",estado:"CE",cod_ibge:2312502)
	Intranet::Cidade.create(municipio:"São Luís do Curu",estado:"CE",cod_ibge:2312601)
	Intranet::Cidade.create(municipio:"Senador Pompeu",estado:"CE",cod_ibge:2312700)
	Intranet::Cidade.create(municipio:"Senador Sá",estado:"CE",cod_ibge:2312809)
	Intranet::Cidade.create(municipio:"Sobral",estado:"CE",cod_ibge:2312908)
	Intranet::Cidade.create(municipio:"Solonópole",estado:"CE",cod_ibge:2313005)
	Intranet::Cidade.create(municipio:"Tabuleiro do Norte",estado:"CE",cod_ibge:2313104)
	Intranet::Cidade.create(municipio:"Tamboril",estado:"CE",cod_ibge:2313203)
	Intranet::Cidade.create(municipio:"Tarrafas",estado:"CE",cod_ibge:2313252)
	Intranet::Cidade.create(municipio:"Tauá",estado:"CE",cod_ibge:2313302)
	Intranet::Cidade.create(municipio:"Tejuçuoca",estado:"CE",cod_ibge:2313351)
	Intranet::Cidade.create(municipio:"Tianguá",estado:"CE",cod_ibge:2313401)
	Intranet::Cidade.create(municipio:"Trairi",estado:"CE",cod_ibge:2313500)
	Intranet::Cidade.create(municipio:"Tururu",estado:"CE",cod_ibge:2313559)
	Intranet::Cidade.create(municipio:"Ubajara",estado:"CE",cod_ibge:2313609)
	Intranet::Cidade.create(municipio:"Umari",estado:"CE",cod_ibge:2313708)
	Intranet::Cidade.create(municipio:"Umirim",estado:"CE",cod_ibge:2313757)
	Intranet::Cidade.create(municipio:"Uruburetama",estado:"CE",cod_ibge:2313807)
	Intranet::Cidade.create(municipio:"Uruoca",estado:"CE",cod_ibge:2313906)
	Intranet::Cidade.create(municipio:"Varjota",estado:"CE",cod_ibge:2313955)
	Intranet::Cidade.create(municipio:"Várzea Alegre",estado:"CE",cod_ibge:2314003)
	Intranet::Cidade.create(municipio:"Viçosa do Ceará",estado:"CE",cod_ibge:2314102)
end
